name: Latest blog post workflow
on:
  schedule:
    # 매일 0시에 실행
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://bellringstar.tistory.com/rss"
          max_post_count: 3
          user_agent: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
          custom_tags: "rss, channel, item, title, link, description, pubDate"
